name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable

      - name: Format
        run: cargo fmt --all -- --check

      - name: Test
        run: cargo test

      - name: Clippy
        run: cargo clippy
