name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Pull Private Submodule CWE_Checker
        env:
          SSHK: ${{ secrets.SUB_CWECHECKER }}
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSHK" > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule update --init -- ./cwe_checker

      - name: Install stable rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
